name: Build and push to github container registry docker containers

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Build frontend.
        run: |
          git clone https://github.com/Vlad1m1/ci-cd-lingua-config .
          cd /frontend
          npm install
          npm run build

      - name: Build monolite container
        run: |
          cd ../server
          mkdir static
          cp -r ../frontend/dist/* static/
          cd ..
          docker compose build
          docker login --username vlad1m1 --password ${{ secrets.GHCR_TOKEN }} ghcr.io
          docker push ghcr.io/vlad1m1/monolite:latest

      - name: Pushing container
        run: |
           docker push ghcr.io/vlad1m1/monolite:latest

      - name: Add SSH key.
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
          
      - name: Connecting to server for DEPLOY THIS.
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "docker stop ghcr-monolite"
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "docker rmi --force ghcr.io/vlad1m1/monolite:latest"
          ssh -o ServerAliveInterval=300 -o ServerAliveCountMax=5 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "docker pull ghcr.io/vlad1m1/monolite:latest && docker pull ghcr.io/vlad1m1/monolite:latest"
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "docker run -d --name ghcr-monolite -p 80:80 ghcr.io/vlad1m1/monolite:latest"

      - name: Cleaning up.
        run: |
          rm -rf ~/.ssh

  
