name: Build and push to github container registry docker containers

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Build containers.
        run: |
          docker compose build

      - name: Pushing container
        run: |
          docker login --username vlad1m1 --password ${{ secrets.GHCR_TOKEN }} ghcr.io
          docker push ghcr.io/vlad1m1/frontend:latest
          docker push ghcr.io/vlad1m1/backend:latest

      - name: Add SSH key.
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
          
      - name: Connecting to server for DEPLOY THIS.
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "docker pull ghcr.io/vlad1m1/frontend:latest"
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "docker pull ghcr.io/vlad1m1/backend:latest"
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "docker run -d --name ghcr-frontend ghcr.io/vlad1m1/frontend:latest"
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "docker run -d --name ghcr-backend ghcr.io/vlad1m1/backend:latest"

      - name: Cleaning up.
        run: |
          rm -rf ~/.ssh
          rm -rf ~/ci-cd-lingua-config

  
